
const fv_list = [
    {ru: "ГЛОРИЯ", en: "Gloria"},
    {ru: "ЯНТАРЬ", en:"Yantar"},
    {ru: "КАЛАМ", en: "Kalam"},
    {ru: "КАЛКАН", en: "Kalkan"},
    {ru: "ЛАГАРТ", en: "Lagart"},
    {ru: "ТАРПОН", en: "Tarpon"},
    {ru: "ТИБУРОН", en: "Tiburon"},
    {ru: "БЛАНКЕТ", en: "Blanket"},
    {ru: "ГРУПЕР", en: "Gruper"},
    {ru: "АЛАНЕТТ", en: "Alanett"},
    {ru: "ТОМКОД", en: "Tomkod"},
    {ru: "ЮГО ВОСТОК 5", en: "Yugo Vostok 5"},
    {ru: "ЮГО-ВОСТОК 3", en: "Yugo Vostok 3"},
    {ru: "ЮГО ВОСТОК 3", en: "Yugo Vostok 3"},
    {ru: "ВИКТОРИЯ 3", en: "Victoria 3"},
    {ru: "ГУРД", en: "Gurd"},
    {ru: "ШКИПЕР", en: "Shkiper"},
    {ru: "АЛЬБАТРОС-8", en: "Albatros 8"},
    {ru: "ДИНАР", en: "Dinar"},
    {ru: "ТАЛЕР", en: "Taler"},
    {ru: "ТАРИ", en: "Tari"},
    {ru: "К.ЭМЕРАЛЬДА", en: "K.Emeralda"},
    {ru: "АФАЛИНА", en: "Afalina"},
    {ru: "САРДА", en: "Sarda"},
    {ru: "ДАЛЛИЯ", en: "Dallia"},
    {ru: "ОСТРОВНОЙ-9", en: "Ostrovnoy-9"},
    {ru: "МЕРЛАНГ", en: "Merlang"},
    {ru: "КОМАНДОР", en: "Komandor"},
    {ru: "ВОСТОК-6", en: "Vostok-6"},
    {ru: "ВОСТОК 6", en: "Vostok-6"},
    {ru: "ВОСТОК-7", en: "Vostok-7"},
    {ru: "ВОСТОК 7", en: "Vostok-7"},
    {ru: "ТРИУМФ", en: "Triumf"},
    {ru: "ДЕМОКРАТ ЛЕОНОВ", en: "Demokrat Leonov"},
    
    { ru: 'НО.81 ЧОНГ ЁНГ', en: 'NO.81 CHONG YONG' },
    { ru: 'НО.83 ЧОНГ ЁНГ', en: 'NO.83 CHONG YONG' },
    { ru: 'БОРИС ТРОФИМЕНКО', en: 'BORIS TROFIMENKO' },
    { ru: 'БОРОДИНО', en: 'BORODINO' },
    { ru: 'АЛДАН', en: 'ALDAN' },
    { ru: 'ИВАН МОШЛЯК', en: 'IVAN MOSHLYAK' },
    { ru: 'КАЛТАН', en: 'KALTAN' },
    { ru: 'КАМЧАТКА ХАРВЕСТ', en: 'KAMCHATKA HARVEST' },
    { ru: 'ХОТИН', en: 'KHOTYN' },
    { ru: 'XXVII СЪЕЗД КПСС', en: 'XXVII CONGRESS OF THE CPSU' },      
    { ru: 'АНАТОЛИЙ ПОНОМАРЕВ', en: 'ANATOLY PONOMAREV' },
    { ru: 'МАТВЕЙ КУЗЬМИН', en: 'MATVEY KUZMIN' },
    { ru: 'АЛЕКСАНДР КСЕНОФОНТОВ', en: 'ALEXANDER KSENOFONTOV' },      
    { ru: 'XX СЪЕЗД ВЛКСМ', en: 'XX CONGRESS OF THE Komsomol' },       
    { ru: 'ВОСТОК-1', en: 'VOSTOK-1' },
    { ru: 'ВОСТОК-5', en: 'VOSTOK-5' },
    { ru: 'ВОСТОК-3', en: 'VOSTOK-3' },
    { ru: 'ВОСТОК-8', en: 'VOSTOK-8' },
    { ru: 'ВОСТОК-4', en: 'VOSTOK-4' },
    { ru: 'МЫС ЛОВЦОВА', en: 'CAPE LOVTSOV' },
    { ru: 'МЫС МУРАВЬЕВА', en: 'CAPE MURAVYEV' },
    { ru: 'ТЕНОР', en: 'TENOR' },
    { ru: 'ЗАЛИВ ВОСТОК', en: 'BAY EAST' },
    { ru: 'КАПИТАН ЕФРЕМОВ', en: 'CAPTAIN EFREMOV' },
    { ru: 'АНИВА', en: 'ANIVA' },
    { ru: 'ОСТРОВ САХАЛИН', en: 'SAKHALIN ISLAND' },
    { ru: 'КАПИТАН ТЕПЛЮКОВ', en: 'CAPTAIN TEPLYUKOV' },
    { ru: 'ВАЛЕРИЙ МАСЛАКОВ', en: 'VALERY MASLAKOV' },
    { ru: 'АЛЕУТ', en: 'ALEUT' },
    { ru: 'ЕЛИЗОВО', en: 'ELIZOVO' },
    { ru: 'КИШИНЕВКА', en: 'CHISINAU' },
    { ru: 'ЦАРЬ', en: 'TSAR' },
    { ru: 'ПРОЛИВ ЛОНГА', en: 'PROLIV LONGA' },
    { ru: 'СВЯТОЙ ВЛАДИМИР', en: 'SAINT VLADIMIR' },
    { ru: 'МЫС ТУРАЛИ', en: 'CAPE TURALI' },
    { ru: 'САНФИШ', en: 'SUNFISH' },
    { ru: 'КАЛЫГИРЬ', en: 'KALYGIR' },
    { ru: 'ЮМИР', en: 'YUMIR' },
    { ru: 'ЯНТАРЬ 31', en: 'YANTAR 31' },
    { ru: 'МЫС ЛЕВЕНОРНА', en: 'CAPE LEVENORNA' },
    { ru: 'МЕРЛАНГ', en: 'MERLANG' },
    { ru: 'ДАЛЛИЯ', en: 'DALLIA' },
    { ru: 'АВАЧА', en: 'AVACHA' },
    { ru: 'МЫС ДАТТА', en: 'CAPE DATTA' },
    { ru: 'ОСТРОВ ИТУРУП', en: 'ITURUP ISLAND' },
    { ru: 'ВЛАДИМИР СТАРЖИНСКИЙ', en: 'VLADIMIR STARZHINSKY' },        
    { ru: 'ГЕРМЕС', en: 'HERMES' },
    { ru: 'ПАРНАС', en: 'PARNASSUS' },
    { ru: 'ФЕНИКС', en: 'PHOENIX' },
    { ru: 'ПРОМЕТЕЙ', en: 'PROMETHEUS' },
    { ru: 'КАМЛАЙН', en: 'CAMLINE' },
    { ru: 'СИРИУС', en: 'SIRIUS' },
    { ru: 'ГЕРКУЛЕС', en: 'HERCULES' },
    { ru: 'АПОЛЛОН', en: 'APOLLO' },
    { ru: 'Кайрос', en: 'Kairos' },
    { ru: 'АНТЕЙ', en: 'ANTEI' },
    { ru: 'ДИОНИС', en: 'DIONYSUS' },
    { ru: 'АНТАРЕС', en: 'ANTARES' },
    { ru: 'ЗЕВС', en: 'ZEUS' },
    { ru: 'ЛИНДГОЛЬМ', en: 'LINDHOLM' },
    { ru: 'ВИКТОРИЯ 3', en: 'VICTORIA 3' },
    { ru: 'АДМИРАЛ КОЛЧАК', en: 'ADMIRAL KOLCHAK' },
    { ru: 'МЫС РУБИКОН', en: 'CAPE RUBICON' },
    { ru: 'ПОРФИРИЙ ЧАНЧИБАДЗЕ', en: 'PORFIRY CHANCHIBADZE' },
    { ru: 'МОРСКОЙ ВОЛК', en: 'SEA WOLF' },
    { ru: 'РАВАРА', en: 'RAVARA' },
    { ru: 'БАГРАТИОН', en: 'BAGRATION' },
    { ru: 'МЫС КУРБАТОВА', en: 'CAPE KURBATOV' },
    { ru: 'ВИКТОР ГАВРИЛОВ', en: 'VIKTOR GAVRILOV' },
    { ru: 'ИХТИОЛОГ', en: 'ICHTHYOLOGIST' },
    { ru: 'ПЛАНЕТА', en: 'PLANET' }
]

exports.fv_list = fv_list

